import Head from 'next/head'
import Image from 'next/image'
import {useEffect} from 'react'
import {studio_form as StudioForm} from 'sauveur.js'

const model = [
    {type: 'input',name:'primary_contact_phone',title:'Whatsapp Number', values:{placeholder:'Whatsapp Number', type:'tel'}},
    {type: 'input',name:'test',title:'Whatsapp Number', values:{placeholder:'Whatsapp Number', type:'tel'}}

]
export default function Home() {
    useEffect(() => {

    },[])

    const submitHandler = () => {
        console.log('submited')
    }
  return (
    <div className={`w-screen h-screen flex  bg-black`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <StudioForm submitHandler={submitHandler} formConfig={model}/>

    </div>
  )
}
