import Head from 'next/head'
import {useEffect} from 'react'
import Studio from 'sauveur.js'

const model = [
    {type: 'input',name:'name',title:'Name', values:{placeholder:'John Doe', type:'tel'}}

]
export default function Home() {
    useEffect(() => {
    },[])

    const submitHandler = (e) => {
        console.log('submited', e)
    }
  return (
    <div className={`w-screen h-screen flex  bg-black justify-center`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Studio.Form submitHandler={submitHandler} formConfig={model}/>

    </div>
  )
}
